### ISSUE TITLE
Refactor code to be more self contained.

### ISSUE THREAD

**Issue by dbuksbaum** [baconandgames/scene-manager-plus-v1.1#1]
The current implementation requires a Menus folder with the loading_scene. However, if the game structure doesnt have this, using this code will create a parallel game structure with assumptions. Everything needed for this component should be self contained, similar to a plug in.

**Comment by baconandgames** [comment]
I don't have plants to update this code. It has been moved into my game template project, which serves as a starting point for a project and by virtue of that has the necessary structure. You're welcome to fork this and make adjustments to suit your needs.
